In [ ]:
from geopy.geocoders import Nominatim

In [ ]:
import os
import pandas as pd
from geopy.geocoders import Nominatim

In [ ]:
os.getcwd()

In [ ]:
df2 = pd.read_csv(r'/Users/heatherphillips/Library/CloudStorage/OneDrive-TheUniversityofMontana/Capstone/MRA Project/Data/Master Project List.csv')
df2

In [ ]:
geolocator = Nominatim(user_agent="myApp")


df2[['Combined Address', 'location_long']] = df2['Combined Address'].apply(
    geolocator.geocode).apply(lambda x: pd.Series(
        [x.latitude, x.longitude], index=['location_lat', 'location_long']))

In [ ]:
import pandas as pd
import requests

In [ ]:

# if your file is in xlsx-format
#df = pd.read_excel("Random Addresses.xlsx")
#if your file is in csv-format
df = pd.read_csv("Master Project List.csv")
df.head()

In [ ]:
address = df
#Key-value
params = {
     "key" : "AIzaSyDNh4cgsqoLAya9m5RzO_yPi3BrfPX-ogM",
     "address": address
}
base_url = "https://maps.googleapis.com/maps/api/geocode/json?"

In [ ]:
response = requests.get(base_url, params = params).json()
response.keys()
if response ["status"] == "OK":
     geometry = response["results"][0]["geometry"]
print(geometry)

In [ ]:
latitude = geometry["location"]["lat"]
longitude = geometry["location"]["lng"]
print(longitude, latitude)

In [ ]:
def getLocation(address):
    params = {
         "key": "AIzaSyDNh4cgsqoLAya9m5RzO_yPi3BrfPX-ogM",
         "address": address
    }
    response = requests.get(base_url, params = params).json()
    print(reponse.keys())
    if response ["status"] == "OK":
         geometry = response["results"][0]["geometry"]
         latitude = geometry["location"]["lat"]
         longitude = geometry["location"]["lng"]
    return f"{latitude}, {longitude}"
df["latlong"] = df["Address"].map(lambda a: getLocation(a))

In [ ]:
import geocoder
import pandas as pd
import requests


with requests.Session() as session:
    for address in df["Address"]:
        coo = geocoder.osm(address, session=session)
        if coo:
            df.loc[df["Address"] == address, "Long"] = round(coo.osm["x"], 2)
            df.loc[df["Address"] == address, "Lat"] = round(coo.osm["y"], 2)

print(df)

In [ ]:
df

In [ ]:
df.to_csv('out.csv')

In [ ]:
google_maps_api_key = AIzaSyDNh4cgsqoLAya9m5RzO_yPi3BrfPX-ogM

In [2]:
gmaps = GoogleMaps('AIzaSyDNh4cgsqoLAya9m5RzO_yPi3BrfPX-ogM')

In [3]:
addresses = pd.read_csv("Master Project List.csv")
addresses.head()

                       Full_Address
0                    , Missoula, MT
1      110 W Broadway, Missoula, MT
2     250  STATION DR, Missoula, MT
3  201 W FRONT & MAIN, Missoula, MT
4     1021 E Broadway, Missoula, MT

In [4]:
addresses['long'] = ""
addresses['lat'] = ""

In [5]:
addresses

                       Full_Address long lat
0                    , Missoula, MT
1      110 W Broadway, Missoula, MT
2     250  STATION DR, Missoula, MT
3  201 W FRONT & MAIN, Missoula, MT
4     1021 E Broadway, Missoula, MT
5       500 S HIGGINS, Missoula, MT
6      115 W Broadway, Missoula, MT
7      147 W BROADWAY, Missoula, MT
8      145 W FRONT ST, Missoula, MT
9   430 N HIGGINS AVE, Missoula, MT

In [9]:
for x in range(len(addresses)):
    try:
        #time.sleep(1) #to add delay in case of large DFs
        geocode_result = gmaps.geocode(addresses['Full_Address'][x])
        addresses['lat'][x] = geocode_result[0]['geometry']['location'] ['lat']
        addresses['long'][x] = geocode_result[0]['geometry']['location']['lng']
    except IndexError:
        print("Address was wrong...")
    except Exception as e:
        print("Unexpected error occurred.", e )
addresses.head()

                       Full_Address        long        lat
0                    , Missoula, MT -113.994031  46.872128
1      110 W Broadway, Missoula, MT -113.995628  46.872957
2     250  STATION DR, Missoula, MT  -113.99838  46.867528
3  201 W FRONT & MAIN, Missoula, MT -113.996898  46.871843
4     1021 E Broadway, Missoula, MT -113.979303  46.866765

In [11]:
addresses.to_csv('out2.csv')

In [12]:
read_file = pd.read_csv (r'out2.csv')
read_file.to_excel (r'out2.xlsx', index = None, header=True)